version: '3.8'

services:
  airwitness:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_airwitness
    ports:
      - "5010:5010"
    volumes:
      - ./evidencia_compartida:/app/worker/evidencia
      - ./assets_compartidos:/app/wwwroot/assets
      - ./assets_compartidos:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=airwitness_db;Username=airwitness_admin;Password=AirWitnessSQL2026!
      - Security__MasterPassword=AirWitnessPro2026
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: sentinel_db
    restart: always
    environment:
      POSTGRES_USER: airwitness_admin
      POSTGRES_PASSWORD: "AirWitnessSQL2026!"
      POSTGRES_DB: airwitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
