// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinel.Dashboard.Data;

#nullable disable

namespace Sentinel.Dashboard.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418040059_ExpandedRadioStation")]
    partial class ExpandedRadioStation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.MasterAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("MasterAudios");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.MatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceFileName")
                        .HasColumnType("text");

                    b.Property<int>("MasterAudioId")
                        .HasColumnType("integer");

                    b.Property<double>("MatchOffsetSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("RadioStationId")
                        .HasColumnType("integer");

                    b.Property<double>("StreamElapsedSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DetectionTime");

                    b.HasIndex("MasterAudioId");

                    b.HasIndex("RadioStationId");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.RadioStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultMasterPath")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RadioStations");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.MasterAudio", b =>
                {
                    b.HasOne("Sentinel.Dashboard.Models.Data.Agency", "Agency")
                        .WithMany("MasterAudios")
                        .HasForeignKey("AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.MatchRecord", b =>
                {
                    b.HasOne("Sentinel.Dashboard.Models.Data.MasterAudio", "MasterAudio")
                        .WithMany("Matches")
                        .HasForeignKey("MasterAudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Dashboard.Models.Data.RadioStation", "RadioStation")
                        .WithMany("Matches")
                        .HasForeignKey("RadioStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAudio");

                    b.Navigation("RadioStation");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.Agency", b =>
                {
                    b.Navigation("MasterAudios");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.MasterAudio", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Sentinel.Dashboard.Models.Data.RadioStation", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
